export const tracks = [
    {
        id: 1,
        service: 'hh',
        service_title: 'HeadHunter',
        delay_unit: 'month',
        delay_count: 1,
        logo: '/static/images/services/hh.png',
        query: 'PHP разработчик',
        filters: { salary_from: 60000, city: 'Москва' },
        is_active: false,
        next_start: '2022-03-27',
        last_start: '2022-02-27',
        created_at: '2019-03-27',
        updated_at: '2019-03-27',
    },
    {
        id: 2,
        service: 'hh',
        service_title: 'HeadHunter',
        delay_unit: 'day',
        delay_count: 4,
        logo: '/static/images/services/hh.png',
        query: 'React разработчик',
        filters: { salary_from: 50000, city: 'Санкт-Петербург' },
        is_active: true,
        next_start: '2022-03-27',
        last_start: '2022-03-24',
        created_at: '2019-03-27',
        updated_at: '2019-03-27',
    },
    {
        id: 3,
        service: 'hh',
        service_title: 'HeadHunter',
        delay_unit: 'month',
        delay_count: 2,
        logo: '/static/images/services/hh.png',
        query: 'DevOps инженер',
        filters: { salary_from: 100000, city: 'Самара' },
        is_active: false,
        next_start: '2022-03-27',
        last_start: '2022-01-27',
        created_at: '2019-03-27',
        updated_at: '2019-03-27',
    },
];